name: Internal Build

on: 
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  internal_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Container Setup
    - name: Container Setup
      run: apt update
      run: apt install -y \
        autoconf \
        cmake \
        g++-multilib \
        gcc-multilib \
        gettext \
        git \
        gdb \
        lcov \
        libcurl4-openssl-dev \
        libmariadb-dev \
        libmariadb-dev-compat \
        libgcrypt20-dev \
        libtool \
        python3-dev \
        python3-pip
      run: pip3 install pycryptodome
    # End Container Setup
    
    - name: Internal Build Script
      run: bash ${GITHUB_WORKSPACE}/support/scripts/build_internal.sh

    - name: Code-Coverage
      working-directory: ${{github.workspace}}/build
      run: make gcov

    - name: Upload 
      uses: codecov/codecov-action@v1
      with:
        files: 'coverage/*.c.gcov'
