name: Minimal Build

on: 
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  minimal_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Container Setup
    - name: Update
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y libgpg-error-dev libgcrypt20-dev python3 lcov

    - name: Install Python Libraries
      run: sudo pip install pycryptodome
    # End Container Setup
    
    - name: Minimal Build Script
      run: bash ${GITHUB_WORKSPACE}/support/scripts/build_minimal.sh
